# 1. Application Setup
spring.application.name=Resume-to-AI-Portfolio
server.port=9090

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.config.import=classpath:secret.properties
openai.model-name=gpt-6-sol
openai.temperature=0.7
